project:
  type: website
  output-dir: docs
  

website:
  title: "Kwaku-Adu's Blog"
  navbar:
    pinned: true

    # background: secondary
    left:
      - about.qmd
      - sidebar:Endangered-Languages
      - icon: github
        href: https://github.com/kwakuemma1 
        
  sidebar:
    - id: Endangered-Languages
      title: "Endangered Languages"
      style: "docked"
      # collapse-level: 6
      contents: 
        - Endangered-Languages/index.qmd
        - href: Endangered-Languages/eda.qmd
          text: Visual Analysis
        - href: Endangered-Languages/models.qmd
          text: Quantitative Analysis
        - Endangered-Languages/sources.qmd
        - Endangered-Languages/about.qmd
        
        
    - title: "Empty space"

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
   
      
        
# format:
#   html:
#     theme: solar
#     css: styles.css
#     highlight-style: espresso
#     toc: true
#     title-block-banner-color: "#01BAEF"

format:
  html:
    theme: 
      - html/custom.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai



