project:
  type: website
  output-dir: docs
  

website:
  title: "Kwaku-Adu's Blog"
  navbar:
    background: secondary
    left:
      - about.qmd
      - sidebar:Endangered-Languages
      - icon: github
        href: https://github.com/kwakuemma1 
        
  sidebar:
    - id: Endangered-Languages
      title: "Endangered Languages"
      # style: "docked"
      # collapse-level: 6
      contents: 
        - Endangered-Languages/index.qmd
        - Endangered-Languages/eda.qmd
        - Endangered-Languages/models.qmd
        - Endangered-Languages/sources.qmd
        - Endangered-Languages/about.qmd
        
        
    - title: "Empty space"
        
        
format:
  html:
    theme: solar
    css: styles.css
    highlight-style: espresso
    toc: true
    title-block-banner-color: "#01BAEF"



