project:
  type: website
  output-dir: docs
  

website:
  title: "Kwaku-Adu's Blog"
  navbar:
    pinned: true
    background: "#E16462"

    # background: secondary
    left:
      - about.qmd
      - sidebar:Endangered-Languages
      - icon: github
        href: https://github.com/kwakuemma1 
        
  sidebar:
    - id: Endangered-Languages
      title: "Endangered Languages"
      style: "docked"
      # collapse-level: 6
      contents: 
        - Endangered-Languages/index.qmd
        - href: Endangered-Languages/eda.qmd
          text: Visual Analysis
        - href: Endangered-Languages/models.qmd
          text: Quantitative Analysis
        - Endangered-Languages/sources.qmd
        - Endangered-Languages/about.qmd
        
        
    - title: "Empty space"

  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Emmanuel K. A. Yeboah</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>      

   

format:
  html:
    theme: 
      - html/custom.scss
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai



